### ISSUE TITLE
dummy codes.json

### ISSUE THREAD

**Issue by gedw99** [dawenxi-tech/2fa#1]
just wanted to try this out.

```sh
{"time":"2023-11-23T08:13:24.962364+01:00","level":"ERROR","msg":"error to read code file","err":"open codes.json: no such file or directory"}
```

would you be ok with putting a dummy "codes-template.json" into the repo ?

**Comment by heramerom** [comment]
Hi, thank you for try. 
The `codes.json` is just for local develop. Please use `make macos` to build a release package. For now, it's only support macos and still in developing. In few days later, it will suport Windows and Linux.

In fact, the `codes.json` has no effect to run the application, when you add a new 2fa code, it will create automatic.

**Comment by gedw99** [comment]
ok thanks @DawenxiTech
