### ISSUE TITLE
Systray

### ISSUE THREAD

**Issue by gedw99** [dawenxi-tech/2fa#9]
here is one to try out

https://github.com/dirslashls/windows11-systray-gioui

**Comment by heramerom** [comment]
Thank you. I will have a try.

**Comment by gedw99** [comment]
works great !

<img width="582" alt="Screenshot 2023-11-29 at 10 31 49" src="https://github.com/dawenxi-tech/2fa/assets/53147028/5df12dbd-9877-44bf-aed4-6a9a04864b30">

I think we can close this for now.
